import javax.swing.*;

/**
 *
 * @author utkus
 */
public class MainMenu extends javax.swing.JFrame {

    PlayGame game1 = new PlayGame();
    JFrame level1 = new JFrame();
    public MainMenu() {

        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        panelFirst = new javax.swing.JPanel();
        btnNewgame = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        lblSpaceship = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GALAXY BALL");
        setBackground(new java.awt.Color(0, 255, 0));
        setName("frameMainMenu"); // NOI18N

        panelFirst.setBackground(new java.awt.Color(51, 51, 51));
        panelFirst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelFirst.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelFirstComponentShown(evt);
            }
        });

        btnNewgame.setBackground(new java.awt.Color(135, 132, 230));
        btnNewgame.setForeground(new java.awt.Color(255, 255, 255));
        btnNewgame.setText("New Game");
        btnNewgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewgameActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(161, 201, 239));
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Help");

        btnOptions.setBackground(new java.awt.Color(161, 201, 239));
        btnOptions.setForeground(new java.awt.Color(255, 255, 255));
        btnOptions.setText("Options");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(161, 201, 239));
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        lblSpaceship.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/backgroundSpaceship3.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GALAXY BALL");

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/backgroundStars.gif"))); // NOI18N

        javax.swing.GroupLayout panelFirstLayout = new javax.swing.GroupLayout(panelFirst);
        panelFirst.setLayout(panelFirstLayout);
        panelFirstLayout.setHorizontalGroup(panelFirstLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(120, 120, 120).addComponent(jLabel1))
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(50, 50, 50).addComponent(lblSpaceship,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(230, 230, 230).addComponent(btnAbout,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(230, 230, 230).addComponent(btnNewgame,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(230, 230, 230).addComponent(btnHelp,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFirstLayout.createSequentialGroup().addGap(230, 230, 230).addComponent(btnOptions,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lblBackground));
        panelFirstLayout
                .setVerticalGroup(panelFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFirstLayout.createSequentialGroup().addGap(20, 20, 20).addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(lblSpaceship, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0).addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFirstLayout.createSequentialGroup().addGap(70, 70, 70).addComponent(btnNewgame,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFirstLayout.createSequentialGroup().addGap(190, 190, 190).addComponent(btnHelp,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFirstLayout.createSequentialGroup().addGap(130, 130, 130).addComponent(
                                btnOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblBackground));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelFirst,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelFirst,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void panelFirstComponentShown(java.awt.event.ComponentEvent evt) {
        // TODO add your handling code here:
    }

    private void btnNewgameActionPerformed(java.awt.event.ActionEvent evt) {
        
        setVisible(false);
        level1.setTitle("Level1-Earth");
        level1.setResizable(false);
        level1.setBounds(10, 70, 700, 600);
        level1.setVisible(true);
        level1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        level1.add(game1);
        
    }

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(panelFirst, "Utku Sapaz\n2021 CSE212 Term Project\nArkanoid Game Java");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        String filepath = "music/SilverSurfer.wav";
        PlayMusic music = new PlayMusic();
        music.playMusic(filepath);


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);

            }
        });
    }







    // Variables declaration - do not modify
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNewgame;
    private javax.swing.JButton btnOptions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblSpaceship;
    private javax.swing.JPanel panelFirst;
    // End of variables declaration
}